#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from fun_project
import fun_project
from fun_project.lib import try_me

if __name__ == '__main__':
    try_me()
